# Generated by Django 3.1.6 on 2021-04-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatingCounterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album', models.CharField(max_length=200, verbose_name='Album')),
                ('Rating', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rating',
            },
        ),
    ]
