# Generated by Django 3.2 on 2021-04-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RatingCounter', '0002_auto_20210408_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingcountermodel',
            name='Album',
            field=models.CharField(max_length=400, unique=True, verbose_name='Album'),
        ),
    ]
