# Generated by Django 3.2 on 2021-04-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RatingCounter', '0003_alter_ratingcountermodel_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingcountermodel',
            name='Album',
            field=models.CharField(max_length=400, verbose_name='Album'),
        ),
    ]
