# Generated by Django 3.2 on 2021-04-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RatingCounter', '0007_auto_20210408_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingcountermodel',
            name='updates_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
