# Generated by Django 3.2 on 2021-04-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RatingCounter', '0008_ratingcountermodel_updates_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingcountermodel',
            options={'ordering': ['-rating'], 'verbose_name': 'Ratings'},
        ),
    ]
