# Generated by Django 3.1.6 on 2021-04-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RatingCounter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingcountermodel',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ratingcountermodel',
            name='Album',
            field=models.CharField(max_length=400, verbose_name='Album'),
        ),
    ]
