# Generated by Django 3.2 on 2021-04-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RatingCounter', '0006_auto_20210408_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingcountermodel',
            options={'verbose_name': 'Ratings'},
        ),
        migrations.RenameField(
            model_name='ratingcountermodel',
            old_name='Album',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='ratingcountermodel',
            old_name='Rating',
            new_name='rating',
        ),
    ]
